### ISSUE TITLE
Describe logbook in more detail

### ISSUE THREAD

**Issue by iezqrom** [poulet-lab/project-template#4]
This is great! I actually was doing something similar in my mono repo :P see image
![image](https://github.com/poulet-lab/project-template/assets/42712006/2bc6cccd-fa9e-471d-be30-5444b2298581)

I think there needs to be more information in the parent readme including the columns, etc. There could also be helper functions. Making separate issue for this.

**Comment by vkaramanis** [comment]
should i close this?

**Comment by iezqrom** [comment]
sure
